# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# #################
#
# For Reference see also https://jekyllrb.com/docs/configuration/options/
#
# #################

# see also https://stackoverflow.com/a/27400343
# baseurl: "" # see also github workflow: bundle exec jekyll build --baseurl <github variable>
url: "https://nobutthefrog.com" # the base hostname & protocol for your site, e.g. http://example.com
development_url: "https://chrisongthb.github.io" # see metadata.html

excerpt_separator: '<!--more-->'

# shorten blogpost links
permalink: :categories/posts/:title/

# Build settings
plugins:
  - jekyll-feed

# used by jekyll-feed
title: 'Nobutthefrog'
author: 'Nobutthefrog'
description: 'We are trying to catch the best waves driving around europe and are searching for people, who connect with our vibes and our music.'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
